### ISSUE TITLE
Can't deploy on k8s

### ISSUE THREAD

**Issue by arezvani** [k8spin/prometheus-multi-tenant-proxy#48]
Hi,
I use [this](https://github.com/k8spin/prometheus-multi-tenant-proxy/blob/master/deployments/kubernetes.yaml) to deploy on k8s but I think some of args like --reload-interval=5 are removed. I removed this arg but my pod not getting ready. With v1.4.0 everything work as expected.
Please help me
Thank you

**Comment by angelbarrera92** [comment]
I have it running with the same deployment hosted in the repository. the --reload-inverval flag is still present in the new release. 
What's the error?

**Comment by arezvani** [comment]
I use latest tag that is my problem. When I use v1.5.0 everything is ok.

**Comment by angelbarrera92** [comment]
> I use latest tag that is my problem. When I use v1.5.0 everything is ok.

Ill take a look to the latest tag. Anyway, ill close the issue :)
