### ISSUE TITLE
Support for JWT-based authentication

### ISSUE THREAD

**Issue by atifazad** [k8spin/prometheus-multi-tenant-proxy#50]
Currently, the proxy only supports basic auth with a fixed configuration for namespaces; this issue's goal is to add support for JWT-based authentication, including fetching the namespace(s) (and/or other filters, see #51 ) from the token itself.

The use case is to offload the decision of what namespaces a request has access to to a different service and let thus the proxy be fully dynamic and not need any configuration about the content of the Prometheus cluster.

Ideally, support for a quick asymmetric signature algorithm (e.g. `EdDSA with Ed25519` and `SHA-512`) that allows to avoid sharing the private key with the proxy would be provided.

**Comment by derlin** [comment]
@angelbarrera92, what do you think?

**Comment by angelbarrera92** [comment]
Ill check it on the upcoming days :)
