### ISSUE TITLE
Create helm chart

### ISSUE THREAD

**Issue by angelbarrera92** [k8spin/prometheus-multi-tenant-proxy#57]
This project doesn't provide a way to install it by helm, it worth trying to create a helm chart and host it on github pages.

**Comment by angelbarrera92** [comment]
It must be similar or equal to the one i crafter for: https://github.com/angelbarrera92/k8s-tunnel-controller/commit/29d4b42da081113c1b609740c6f6cc9c47fe6682

**Comment by derlin** [comment]
I would be interested in taking this one, will see if I find the time.

**Comment by derlin** [comment]
Well, I will let you take it then (very good point!)
I will take the white-list stuff instead 😉

**Comment by angelbarrera92** [comment]
Will be available since v1.10.0
