### ISSUE TITLE
Enable configuration using environment variables

### ISSUE THREAD

**Issue by angelbarrera92** [k8spin/prometheus-multi-tenant-proxy#62]
@derlin introduced a new configuration parameter (for aws signing) on the latest release. It can be configured either by an environment variable or by flag in the `cli`.

It would be nice to have the other parameters to be configurable by environment variables.
It must have the same prefix @derlin used for the aws signing feature. 

Thanks!

**Comment by derlin** [comment]
I can take care of this one 😊
