### ISSUE TITLE
Endpoint whitelist

### ISSUE THREAD

**Issue by derlin** [k8spin/prometheus-multi-tenant-proxy#68]
As hinted in `reverse_test.go`, prometheus exposes other endpoints than just the ones for querying: `status`, `alerts`, etc. With the current implementation, as long as you have a valid authentication, you should be able to query any of those without issues, which could leak very sensitive information.

I would propose to add a whitelist feature: the ability to restrict access to only specific API endpoints.
The whitelist could be set by default to `/series`, `/query` and `/query_range`, as they are the ones we inject labels to.

The whitelist should however be configurable, as we do with the unprotected endpoints.

What do you think?

**Comment by angelbarrera92** [comment]
I didn't thought about it before.

Absolutely, we must restrict accessing other endpoints apart from the `/series`, `/query` and `/query_range` and the health checks.
Then, enabling others by whitelisting (configuration parameter)
